blog/urls.py
from django.urls import path
from .views import (
    BlogHomePageView,
    PostDetailView,
)

app_name='blog'


urlpatterns = [
    path('', BlogHomePageView.as_view(), name='home'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post-detail'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    HomePageView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',HomePageView.as_view(), name='home'),
    path('blog/',include('blog.urls',namespace='blog')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class PostObjects(models.Manager):
    def get_queryset(self):
        return super().get_queryset() .filter(status='published')

class Post(models.Model):
    postobjects = PostObjects()

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),    
        )


    category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
    title = models.CharField(max_length=255)
    excerpt = models.TextField(null=True)
    content = models.TextField()
    slug = models.SlugField(max_length=255, unique_for_date='published', null=False, unique=False)
    published = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='blog_posts')
    status = models.CharField(max_length=10, choices=options, default='draft')

    class Meta:
        ordering = ('-published',)

    def __str__(self):
        return self.title



class Comment(models.Model):

    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=50)
    email = models.EmailField()
    content = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ('publish',)

    def __str__(self):
        return f"Comentado por {self.name}"

blog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView
from .models import Post
from django.utils.safestring import mark_safe

# Create your views here.

class BlogHomePageView(TemplateView):
    template_name = "blog/index.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["posts"] = Post.postobjects.all()
        return context



class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post-detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = Post.postobjects.filter(slug=self.kwargs.get('slug'))

        # Marcamos el contenido como seguro
        #post.content = mark_safe(post.content)
        context['post'].content = mark_safe(context['post'].content)
        return context

core/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = 'index.html'

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} {% endblock title %}</title>
    {% block style %} {% endblock style%}
</head>

<body>
  <div class="main_nav">
    <ul class="navlist">
      <li class="active"><a href="#" id="current">Home</a></li>
      <li><a href="#">About</a></li>
      <li><a href="#">Links</a></li>
      <li><a href="#">Fun</a></li>
      <li><a href="#">Contact</a></li>
    </ul>
  </div>
  <div id="content">
    {% block content %} {% endblock content %}
  </div>
</body>
</html>

templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Blog {% endblock title %}
{% block style %}<link rel="stylesheet" href="{% static 'css/blog.css' %}"> {% endblock style %}

{% block content %} 
  <div class="blog-header">
    <img src="{% static 'images/ancap.jpg' %}" alt="Cabecera del Blog" class="blog-header-image">
  </div>
  <h1> blog </h1>
  {% for post in posts %}
    <div class="post-item"> 
      <h2><a href="{% url 'blog:post-detail' slug=post.slug %}">{{ post.title }}</a></h2>
      <p class="post-meta">Publicado el {{ post.published }}</p> 
      <div class="post-excerpt">{{ post.excerpt|truncatechars:150 }}</div> 
      <a href="{% url 'blog:post-detail' slug=post.slug %}" class="read-more">Leer más</a> 
    </div>
  {% endfor %}
{% endblock content%}

templates/blog/post-detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %} {{ post.title }} {% endblock title %}

{% block style %}<link rel="stylesheet" href="{% static 'css/blog.css' %}"> {% endblock style%}

{% block content %}
  <div class="background">
    <article class="blog-post">
      <h1>{{ post.title }}</h1>
      <p class="post-meta">Published on {{ post.published }} by {{ post.author }}</p>

      {% if post.excerpt %}
        <p class="post-excerpt">{{ post.excerpt }}</p>
      {% endif %}

      <div class="post-content">
        {{ post.content }}
      </div>
    </article>
  </div>
  <div class="background2">hola\n</div>
{% endblock content %} 

templates/index.html
{% extends "base.html" %}

{% block title%} Home {% endblock title%}


{% block content%} 
    <h1>Home page</h1>
{% endblock content %}